# Generated by Django 4.2.30 on 2026-05-27 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='项目名称')),
                ('description', models.TextField(blank=True, default='', verbose_name='项目描述')),
                ('repo_url', models.URLField(blank=True, default='', verbose_name='仓库地址')),
                ('status', models.CharField(choices=[('pending', '待审计'), ('in_progress', '审计中'), ('completed', '已完成'), ('failed', '审计失败')], default='pending', max_length=20, verbose_name='项目状态')),
                ('language', models.CharField(default='Python', max_length=50, verbose_name='编程语言')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '待审计项目',
                'verbose_name_plural': '待审计项目',
                'db_table': 'project',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CodeFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(max_length=500, verbose_name='文件路径')),
                ('content', models.TextField(verbose_name='文件内容')),
                ('language', models.CharField(default='Python', max_length=50, verbose_name='编程语言')),
                ('line_count', models.PositiveIntegerField(default=0, verbose_name='代码行数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='code_files', to='audit.project', verbose_name='所属项目')),
            ],
            options={
                'verbose_name': '代码文件',
                'verbose_name_plural': '代码文件',
                'db_table': 'code_file',
                'ordering': ['file_path'],
            },
        ),
        migrations.CreateModel(
            name='AuditRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_type', models.CharField(max_length=100, verbose_name='问题类型')),
                ('description', models.TextField(verbose_name='问题描述')),
                ('severity', models.CharField(choices=[('low', '低'), ('medium', '中'), ('high', '高'), ('critical', '严重')], default='medium', max_length=20, verbose_name='严重程度')),
                ('original_code', models.TextField(verbose_name='原始代码片段')),
                ('suggested_fix', models.TextField(blank=True, default='', verbose_name='修复建议')),
                ('similar_cases', models.JSONField(blank=True, default=list, verbose_name='相似历史案例')),
                ('similarity_score', models.FloatField(default=0.0, verbose_name='相似度得分')),
                ('is_fixed', models.BooleanField(default=False, verbose_name='是否已修复')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('code_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_records', to='audit.codefile', verbose_name='审计文件')),
            ],
            options={
                'verbose_name': '审计重构记录',
                'verbose_name_plural': '审计重构记录',
                'db_table': 'audit_record',
                'ordering': ['-created_at'],
            },
        ),
    ]
